# A1 Robot Configuration
name: a1
urdf_path: assets/robots/a1/urdf/a1.urdf
num_joints: 12
joint_names:
  - FL_hip_joint
  - FL_thigh_joint
  - FL_calf_joint
  - FR_hip_joint
  - FR_thigh_joint
  - FR_calf_joint
  - RL_hip_joint
  - RL_thigh_joint
  - RL_calf_joint
  - RR_hip_joint
  - RR_thigh_joint
  - RR_calf_joint

default_joint_positions:
  - 0.0   # FL_hip_joint
  - 0.9   # FL_thigh_joint
  - -1.8  # FL_calf_joint
  - 0.0   # FR_hip_joint
  - 0.9   # FR_thigh_joint
  - -1.8  # FR_calf_joint
  - 0.0   # RL_hip_joint
  - 0.9   # RL_thigh_joint
  - -1.8  # RL_calf_joint
  - 0.0   # RR_hip_joint
  - 0.9   # RR_thigh_joint
  - -1.8  # RR_calf_joint

joint_limits:
  FL_hip_joint: [-1.22, 1.22]
  FL_thigh_joint: [-2.77, 2.77]
  FL_calf_joint: [-2.77, 2.77]
  FR_hip_joint: [-1.22, 1.22]
  FR_thigh_joint: [-2.77, 2.77]
  FR_calf_joint: [-2.77, 2.77]
  RL_hip_joint: [-1.22, 1.22]
  RL_thigh_joint: [-2.77, 2.77]
  RL_calf_joint: [-2.77, 2.77]
  RR_hip_joint: [-1.22, 1.22]
  RR_thigh_joint: [-2.77, 2.77]
  RR_calf_joint: [-2.77, 2.77]

mass: 12.0
base_dimensions: [0.366, 0.094, 0.114]  # length, width, height
motor_strength: 33.5  # Nm
